version: '3.3'

x-aws-loadbalancer: $API_AWS_LOADBALANCER

x-aws-cloudformation:
  Resources:
    ApiTCP80Listener:
      Properties:
        DefaultActions:
          - Type: redirect
            RedirectConfig:
              Port: 443
              Protocol: HTTPS
              StatusCode: HTTP_301

    ApiTCP443Listener:
      Properties:
        Port: 443
        Protocol: HTTPS
        Certificates:
          - $API_AWS_CERTIFICATE
        DefaultActions:
          - Type: "fixed-response"
            FixedResponseConfig:
              ContentType: "text/plain"
              MessageBody: "BAD DOMAIN NAME"
              StatusCode: "200"

    ApiTCP443TargetGroup:

    ApiService:
      Properties:
        LoadBalancers:
          - ContainerName: api
            ContainerPort: 80
            TargetGroupArn:
              Ref: ApiTCP80TargetGroup

    ApiTCP443BaseRule:
      Type: AWS::ElasticLoadBalancingV2::ListenerRule
      Properties:
        ListenerArn:
          Ref: ApiTCP443Listener
        Priority: 50000
        Conditions:
          - Field: host-header
            HostHeaderConfig:
              Values:
                - $API_AWS_HOSTNAME
        Actions:
          - Type: forward
            ForwardConfig:
              TargetGroups:
                - TargetGroupArn:
                    Ref: ApiTCP80TargetGroup

services:
  api:
    image: $API_AWS_IMAGE
    x-aws-pull_credentials: $API_AWS_PULL
    ports:
      - "80:80"
      - "443:443"
    env_file: ./docker/api/.env
    environment:
      - ROCKET_PORT=80
